# Detekt configuration file
# Excludes test files from code scanning
# excludes magic numbers, return count, long parameter, long methods

style:
  MaxLineLength:
    active: true
    maxLineLength: 1400
    excludePackageStatements: true
    excludeImportStatements: true
    excludeCommentStatements: false
    excludeRawStrings: true

  ForbiddenComment:
    active: false

  MagicNumber:
    active: false

  ReturnCount:
    active: false

  LoopWithTooManyJumpStatements:
    active: false

naming:
  FunctionNaming:
    active: true
    ignoreAnnotated:
      - 'Composable'

exceptions:
  TooGenericExceptionCaught:
    active: true
    exceptionNames:
      - Throwable
      - Error

coroutines:
  RedundantSuspendModifier:
    active: false

complexity:
  TooManyFunctions:
    active: false

  LargeClass:
    active: false

  LongParameterList:
    active: false

  LongMethod:
    active: false

  ComplexCondition:
    active: false

  NestedBlockDepth:
    active: false

  CyclomaticComplexMethod:
    active: true
    allowedComplexity: 35
    ignoreSingleWhenExpression: true
    ignoreSimpleWhenEntries: true
    ignoreNestingFunctions: true
