name: Android Build

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:  # Ermöglicht manuelles Auslösen

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew assembleFdroidFullDebug
      
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: app/build/outputs/apk/fdroidFull/debug/*.apk
        if-no-files-found: error
